# Generated by Django 2.2.7 on 2019-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hydraulique_step_turbinage', models.IntegerField(blank=True, null=True)),
                ('perimetre', models.CharField(max_length=50)),
                ('hydraulique_lacs', models.IntegerField(blank=True, null=True)),
                ('eolien', models.IntegerField(blank=True, null=True)),
                ('hydraulique', models.IntegerField(blank=True, null=True)),
                ('ech_comm_italie', models.IntegerField(blank=True, null=True)),
                ('ech_comm_suisse', models.IntegerField(blank=True, null=True)),
                ('fioul_autres', models.IntegerField(blank=True, null=True)),
                ('prevision_j1', models.IntegerField()),
                ('ech_physiques', models.IntegerField(blank=True, null=True)),
                ('ech_comm_allemagne_belgique', models.CharField(blank=True, max_length=15, null=True)),
                ('solaire', models.IntegerField(blank=True, null=True)),
                ('nucleaire', models.IntegerField(blank=True, null=True)),
                ('gaz_tac', models.IntegerField(blank=True, null=True)),
                ('pompage', models.IntegerField(blank=True, null=True)),
                ('prevision_j', models.IntegerField()),
                ('fioul', models.IntegerField(blank=True, null=True)),
                ('gaz', models.IntegerField(blank=True, null=True)),
                ('nature', models.CharField(max_length=50)),
                ('gaz_cogen', models.CharField(blank=True, max_length=15, null=True)),
                ('gaz_autres', models.IntegerField(blank=True, null=True)),
                ('fioul_cogen', models.IntegerField(blank=True, null=True)),
                ('ech_comm_espagne', models.IntegerField(blank=True, null=True)),
                ('bioenergies_biomasse', models.IntegerField(blank=True, null=True)),
                ('bioenergies_dechets', models.IntegerField(blank=True, null=True)),
                ('taux_co2', models.IntegerField(blank=True, null=True)),
                ('hydraulique_fil_eau_eclusee', models.IntegerField(blank=True, null=True)),
                ('bioenergies_biogaz', models.IntegerField(blank=True, null=True)),
                ('fioul_tac', models.IntegerField(blank=True, null=True)),
                ('gaz_ccg', models.IntegerField(blank=True, null=True)),
                ('date_heure', models.CharField(max_length=25)),
                ('charbon', models.IntegerField(blank=True, null=True)),
                ('bioenergies', models.IntegerField(blank=True, null=True)),
                ('ech_comm_angleterre', models.IntegerField(blank=True, null=True)),
                ('consommation', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
