from django.db import models

class Record(models.Model):
    recordid =  models.CharField(max_length=100, primary_key=True)
    hydraulique_step_turbinage = models.IntegerField(blank=True, null=True) 
    perimetre = models.CharField(max_length=50)
    hydraulique_lacs = models.IntegerField(blank=True, null=True)
    eolien = models.IntegerField(blank=True, null=True)
    hydraulique = models.IntegerField(blank=True, null=True)
    ech_comm_italie = models.IntegerField(blank=True, null=True)
    ech_comm_suisse = models.IntegerField(blank=True, null=True)
    fioul_autres = models.IntegerField(blank=True, null=True)
    prevision_j1 = models.IntegerField()
    ech_physiques = models.IntegerField(blank=True, null=True)
    ech_comm_allemagne_belgique = models.CharField(max_length=15, blank=True, null=True)
    solaire = models.IntegerField(blank=True, null=True)
    nucleaire = models.IntegerField(blank=True, null=True)
    gaz_tac = models.IntegerField(blank=True, null=True)
    pompage = models.IntegerField(blank=True, null=True)
    prevision_j = models.IntegerField()
    fioul = models.IntegerField(blank=True, null=True)
    gaz = models.IntegerField(blank=True, null=True)
    nature = models.CharField(max_length=50)
    gaz_cogen = models.CharField(max_length=15, blank=True, null=True)
    gaz_autres = models.IntegerField(blank=True, null=True)
    fioul_cogen = models.IntegerField(blank=True, null=True)
    ech_comm_espagne = models.IntegerField(blank=True, null=True)
    bioenergies_biomasse = models.IntegerField(blank=True, null=True)
    date = models.DateField()
    bioenergies_dechets = models.IntegerField(blank=True, null=True)
    taux_co2 = models.IntegerField(blank=True, null=True)
    heure = models.TimeField()
    hydraulique_fil_eau_eclusee = models.IntegerField(blank=True, null=True)
    bioenergies_biogaz = models.IntegerField(blank=True, null=True)
    fioul_tac = models.IntegerField(blank=True, null=True)
    gaz_ccg = models.IntegerField(blank=True, null=True)
    date_heure = models.CharField(max_length=25)
    charbon = models.IntegerField(blank=True, null=True)
    bioenergies = models.IntegerField(blank=True, null=True)
    ech_comm_angleterre = models.IntegerField(blank=True, null=True)
    consommation = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.date_heure
